name: ci

on:
  push:

jobs:
  build:
    name: Build on ubuntu-24.04
    if: "contains(github.event.head_commit.message, 'release ubuntu24-php84-mysql84.rv7')"

    runs-on: ubuntu-24.04

    env:
      GIT_MSG: ${{ github.event.head_commit.message }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Check OS Env
        run: |
          localectl status
          cat /proc/cpuinfo
          free -m

      - name: Login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/web:ubuntu24-php84-mysql84.rv7
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build -f src/ubuntu24-php84-mysql84/Dockerfile -t $IMAGE_ID .
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - run: docker image ls

      - name: Push Image
        run: |
          docker push $IMAGE_ID
        env:
          IMAGE_ID: ${{ env.IMAGE_ID }}
